name:                future-haskell-demo
version:             0.1.0.0
github:              "githubuser/future-haskell-demo"
license:             BSD3
author:              "Dima Kurilo"
maintainer:          "dkurilo@gmail.com"
copyright:           "2019 Dima Kurilo"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/future-haskell-demo#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  future-haskell-demo-hello:
    main:                Main.hs
    source-dirs:         hello
    ghc-options:
    - -threaded
    - -O2
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - future-haskell-demo
    - base-unicode-symbols >0.2 && <0.3
  future-haskell-demo-fib:
    main:                Main.hs
    source-dirs:         fib
    ghc-options:
    - -threaded
    - -O2
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - future-haskell-demo
    - base-unicode-symbols >0.2 && <0.3
  future-haskell-demo-fib-memoized:
    main:                Main.hs
    source-dirs:         fib-memoized
    ghc-options:
    - -threaded
    - -O2
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - future-haskell-demo
    - base-unicode-symbols >0.2 && <0.3
  future-haskell-demo:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -O2
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - future-haskell-demo
    - base-unicode-symbols >0.2 && <0.3
    - AhoCorasick >0.0.2
    - bytestring >0.10
    - containers >0.6 && <0.7
    - directory >1.3 && <1.4

  future-haskell-demo-threaded:
    main:                Main.hs
    source-dirs:         app-threaded
    ghc-options:
    - -threaded
    - -O2
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - future-haskell-demo
    - base-unicode-symbols >0.2 && <0.3
    - AhoCorasick >0.0.2
    - bytestring >0.10
    - containers >0.6 && <0.7
    - directory >1.3 && <1.4
    - stm >=2.4 && <2.6

tests:
  future-haskell-demo-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - future-haskell-demo
